// <auto-generated />
using System;
using EduRate.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EduRate.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260726220446_AddPriceToTeacherCenter")]
    partial class AddPriceToTeacherCenter
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EduRate.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAttended")
                        .HasColumnType("bit");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookingDate = new DateTime(2026, 7, 24, 1, 4, 46, 520, DateTimeKind.Local).AddTicks(4081),
                            IsAttended = true,
                            StudentId = 1,
                            TeacherId = 1
                        },
                        new
                        {
                            Id = 2,
                            BookingDate = new DateTime(2026, 7, 26, 1, 4, 46, 520, DateTimeKind.Local).AddTicks(4088),
                            IsAttended = false,
                            StudentId = 2,
                            TeacherId = 2
                        });
                });

            modelBuilder.Entity("EduRate.Models.Center", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Centers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "شارع المحطة",
                            Description = "قاعات مكيفة ومجهزة",
                            IsVerified = true,
                            Latitude = 30.0444,
                            Longitude = 31.235700000000001,
                            Name = "سنتر الأوائل"
                        },
                        new
                        {
                            Id = 2,
                            Address = "وسط البلد",
                            Description = "مراجعات نهائية مكثفة",
                            IsVerified = false,
                            Latitude = 30.033300000000001,
                            Longitude = 31.2333,
                            Name = "سنتر النخبة"
                        });
                });

            modelBuilder.Entity("EduRate.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("SenderRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "يا مستر ممكن تشرح الجزء الأخير تاني؟",
                            IsRead = true,
                            SenderRole = "Student",
                            SentAt = new DateTime(2026, 7, 26, 20, 4, 46, 520, DateTimeKind.Local).AddTicks(4146),
                            StudentId = 1,
                            TeacherId = 1
                        },
                        new
                        {
                            Id = 2,
                            Content = "أكيد، راجع الفيديو اللي نزلته وهتفهمه.",
                            IsRead = false,
                            SenderRole = "Teacher",
                            SentAt = new DateTime(2026, 7, 26, 21, 4, 46, 520, DateTimeKind.Local).AddTicks(4151),
                            StudentId = 1,
                            TeacherId = 1
                        });
                });

            modelBuilder.Entity("EduRate.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("IPAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comment = "Excellent explanation!",
                            CreatedAt = new DateTime(2026, 7, 25, 1, 4, 46, 520, DateTimeKind.Local).AddTicks(4116),
                            IPAddress = "192.168.1.1",
                            IsVerified = true,
                            Rating = 5,
                            StudentId = 1,
                            TeacherId = 1
                        },
                        new
                        {
                            Id = 2,
                            Comment = "Very good.",
                            CreatedAt = new DateTime(2026, 7, 26, 1, 4, 46, 520, DateTimeKind.Local).AddTicks(4122),
                            IPAddress = "192.168.1.5",
                            IsVerified = true,
                            Rating = 4,
                            StudentId = 2,
                            TeacherId = 2
                        });
                });

            modelBuilder.Entity("EduRate.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EducationalLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Governorate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EducationalLevel = "Senior 2",
                            Email = "ahmed@example.com",
                            Governorate = "القاهرة",
                            Name = "Ahmed Khaled",
                            Region = "المعادي"
                        },
                        new
                        {
                            Id = 2,
                            EducationalLevel = "Senior 3",
                            Email = "mona@example.com",
                            Governorate = "الجيزة",
                            Name = "Mona Sayed",
                            Region = "الدقي"
                        });
                });

            modelBuilder.Entity("EduRate.Models.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AverageRating")
                        .HasColumnType("float");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalReviews")
                        .HasColumnType("int");

                    b.Property<double>("TrustScore")
                        .HasColumnType("float");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AverageRating = 4.5,
                            Bio = "Expert in simplifying Physics concepts.",
                            Name = "Mr. Mohammed Ahmed",
                            Subject = "Physics",
                            TotalReviews = 2,
                            TrustScore = 95.0,
                            YearsOfExperience = 10
                        },
                        new
                        {
                            Id = 2,
                            AverageRating = 5.0,
                            Bio = "Specialized in foundational English and grammar.",
                            Name = "Mr. Mahmoud Ali",
                            Subject = "English",
                            TotalReviews = 1,
                            TrustScore = 88.0,
                            YearsOfExperience = 5
                        });
                });

            modelBuilder.Entity("EduRate.Models.TeacherCenter", b =>
                {
                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.Property<int>("CenterId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ProfitPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("TeacherId", "CenterId");

                    b.HasIndex("CenterId");

                    b.ToTable("TeacherCenters");

                    b.HasData(
                        new
                        {
                            TeacherId = 1,
                            CenterId = 1,
                            IsActive = true,
                            JoinDate = new DateTime(2026, 1, 27, 1, 4, 46, 520, DateTimeKind.Local).AddTicks(4012),
                            Price = 120.0m,
                            ProfitPercentage = 70.5m
                        },
                        new
                        {
                            TeacherId = 1,
                            CenterId = 2,
                            IsActive = true,
                            JoinDate = new DateTime(2026, 5, 27, 1, 4, 46, 520, DateTimeKind.Local).AddTicks(4023),
                            Price = 150.0m,
                            ProfitPercentage = 60.0m
                        },
                        new
                        {
                            TeacherId = 2,
                            CenterId = 1,
                            IsActive = false,
                            JoinDate = new DateTime(2025, 7, 27, 1, 4, 46, 520, DateTimeKind.Local).AddTicks(4028),
                            Price = 100.0m,
                            ProfitPercentage = 80.0m
                        });
                });

            modelBuilder.Entity("EduRate.Models.Booking", b =>
                {
                    b.HasOne("EduRate.Models.Student", "Student")
                        .WithMany("Bookings")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduRate.Models.Teacher", "Teacher")
                        .WithMany("Bookings")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("EduRate.Models.Message", b =>
                {
                    b.HasOne("EduRate.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduRate.Models.Teacher", "Teacher")
                        .WithMany("Messages")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("EduRate.Models.Review", b =>
                {
                    b.HasOne("EduRate.Models.Student", "Student")
                        .WithMany("Reviews")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduRate.Models.Teacher", "Teacher")
                        .WithMany("Reviews")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("EduRate.Models.TeacherCenter", b =>
                {
                    b.HasOne("EduRate.Models.Center", "Center")
                        .WithMany("TeacherCenters")
                        .HasForeignKey("CenterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduRate.Models.Teacher", "Teacher")
                        .WithMany("TeacherCenters")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Center");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("EduRate.Models.Center", b =>
                {
                    b.Navigation("TeacherCenters");
                });

            modelBuilder.Entity("EduRate.Models.Student", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("EduRate.Models.Teacher", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Messages");

                    b.Navigation("Reviews");

                    b.Navigation("TeacherCenters");
                });
#pragma warning restore 612, 618
        }
    }
}
