// <auto-generated />
using System;
using EduRate.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EduRate.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260725232538_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EduRate.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("IPAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comment = "شرح ممتاز جداً",
                            CreatedAt = new DateTime(2026, 7, 24, 2, 25, 37, 778, DateTimeKind.Local).AddTicks(7792),
                            IPAddress = "192.168.1.1",
                            IsVerified = true,
                            Rating = 5,
                            StudentName = "طالب مجهول",
                            TeacherId = 1
                        },
                        new
                        {
                            Id = 2,
                            Comment = "كويس بس الحصة طويلة",
                            CreatedAt = new DateTime(2026, 7, 25, 2, 25, 37, 778, DateTimeKind.Local).AddTicks(7798),
                            IPAddress = "192.168.1.5",
                            IsVerified = true,
                            Rating = 4,
                            StudentName = "أحمد خالد",
                            TeacherId = 1
                        });
                });

            modelBuilder.Entity("EduRate.Models.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AverageRating")
                        .HasColumnType("float");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalReviews")
                        .HasColumnType("int");

                    b.Property<double>("TrustScore")
                        .HasColumnType("float");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AverageRating = 4.5,
                            Bio = "Expert in simplifying Physics concepts.",
                            Name = "Mr. Mohammed Ahmed",
                            Subject = "Physics",
                            TotalReviews = 2,
                            TrustScore = 95.0,
                            YearsOfExperience = 10
                        },
                        new
                        {
                            Id = 2,
                            AverageRating = 5.0,
                            Bio = "Specialized in foundational English and grammar.",
                            Name = "Mr. Mahmoud Ali",
                            Subject = "English",
                            TotalReviews = 1,
                            TrustScore = 88.0,
                            YearsOfExperience = 5
                        },
                        new
                        {
                            Id = 3,
                            AverageRating = 3.0,
                            Bio = "Makes math fun and easy to understand.",
                            Name = "Eng. Tarek Hassan",
                            Subject = "Mathematics",
                            TotalReviews = 1,
                            TrustScore = 92.0,
                            YearsOfExperience = 8
                        },
                        new
                        {
                            Id = 4,
                            AverageRating = 5.0,
                            Bio = "Focuses on practical experiments and problem-solving.",
                            Name = "Dr. Sarah Ibrahim",
                            Subject = "Chemistry",
                            TotalReviews = 1,
                            TrustScore = 98.0,
                            YearsOfExperience = 12
                        });
                });

            modelBuilder.Entity("EduRate.Models.Review", b =>
                {
                    b.HasOne("EduRate.Models.Teacher", "Teacher")
                        .WithMany("Reviews")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("EduRate.Models.Teacher", b =>
                {
                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
